/**
 * 自动生成的前端命令路由
 *
 * @generated
 * DO NOT EDIT THIS FILE MANUALLY
 */

import type { CommandResult } from '$lib/types/api.js';
import type { AeryFixParams, AudioPreset, BMSEvent, BmsFolderSetNameType, IProgressManager, RemoveMediaPreset, ReplacePreset, SetFileNumParams, VideoPreset } from '$lib/types/enums.js';

/**
 * 自动生成的前端命令执行函数
 */
export async function executeGeneratedFrontendCommand(
  commandId: string,
  params: Record<string, unknown>
): Promise<CommandResult> {
  try {
    if (commandId === 'is_dir_having_file') {
      const { isDirHavingFile } = await import('$lib/utils/fs/compare.js');
      const result = await isDirHavingFile(params.dirPath as string);
      return { success: true, data: result };
    }

    if (commandId === 'is_dir_having_content') {
      const { isDirHavingContent } = await import('$lib/utils/fs/compare.js');
      const result = await isDirHavingContent(params.dirPath as string);
      return { success: true, data: result };
    }

    if (commandId === 'wasted_fix') {
      const { fix } = await import('$lib/utils/wasted/index.js');
      await fix(params.params as AeryFixParams);
      return { success: true, data: undefined };
    }

    if (commandId === 'rawpack_batch_rename_with_num') {
      const { batchRenameWithNum } = await import('$lib/utils/rawpack/index.js');
      const result = await batchRenameWithNum(params.params as SetFileNumParams);
      return { success: true, data: result };
    }

    if (commandId === 'rawpack_unzip_numeric_to_bms_folder') {
      const { unzipNumericToBmsFolder } = await import('$lib/utils/rawpack/index.js');
      await unzipNumericToBmsFolder(params.packDir as string, params.cacheDir as string, params.rootDir as string, params.confirm as boolean, params.replacePreset as ReplacePreset);
      return { success: true, data: undefined };
    }

    if (commandId === 'rawpack_unzip_with_name_to_bms_folder') {
      const { unzipWithNameToBmsFolder } = await import('$lib/utils/rawpack/index.js');
      await unzipWithNameToBmsFolder(params.packDir as string, params.cacheDir as string, params.rootDir as string, params.confirm as boolean, params.replacePreset as ReplacePreset);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_split_folders_with_first_char') {
      const { splitFoldersWithFirstChar } = await import('$lib/utils/bigpack/split.js');
      await splitFoldersWithFirstChar(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_undo_split_pack') {
      const { undoSplitPack } = await import('$lib/utils/bigpack/split.js');
      await undoSplitPack(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_move_works_in_pack') {
      const { moveWorksInPack } = await import('$lib/utils/bigpack/split.js');
      await moveWorksInPack(params.rootDir as string, params.targetPackName as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_move_out_works') {
      const { moveOutWorks } = await import('$lib/utils/bigpack/split.js');
      await moveOutWorks(params.rootDir as string, params.sourcePackName as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_merge_folders_with_same_name_within_dir') {
      const { mergeFoldersWithSameNameWithinDir } = await import('$lib/utils/bigpack/split.js');
      await mergeFoldersWithSameNameWithinDir(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_move_works_in_pack_python') {
      const { moveWorksInPackPython } = await import('$lib/utils/bigpack/split.js');
      await moveWorksInPackPython(params.fromDir as string, params.toDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_move_works_with_same_name_to_siblings') {
      const { moveWorksWithSameNameToSiblings } = await import('$lib/utils/bigpack/split.js');
      await moveWorksWithSameNameToSiblings(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_move_works_with_same_name') {
      const { moveWorksWithSameName } = await import('$lib/utils/bigpack/split.js');
      await moveWorksWithSameName(params.fromDir as string, params.toDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_merge_split_folders') {
      const { mergeSplitFolders } = await import('$lib/utils/bigpack/merge.js');
      await mergeSplitFolders(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_scan_similar_folders') {
      const { scanSimilarFolders } = await import('$lib/utils/bigpack/similarity.js');
      const result = await scanSimilarFolders(params.rootDir as string, params.similarityTrigger as number);
      return { success: true, data: result };
    }

    if (commandId === 'read_and_parse_bms_file') {
      const { readAndParseBmsFile } = await import('$lib/utils/bms/scanner.js');
      const result = await readAndParseBmsFile(params.filePath as string);
      return { success: true, data: result };
    }

    if (commandId === 'get_dir_bms_list') {
      const { getDirBmsList } = await import('$lib/utils/bms/scanner.js');
      const result = await getDirBmsList(params.dirPath as string);
      return { success: true, data: result };
    }

    if (commandId === 'get_dir_bms_info') {
      const { getDirBmsInfo } = await import('$lib/utils/bms/scanner.js');
      const result = await getDirBmsInfo(params.dirPath as string);
      return { success: true, data: result };
    }

    if (commandId === 'is_work_dir') {
      const { isWorkDir } = await import('$lib/utils/bms/scanner.js');
      const result = await isWorkDir(params.dirPath as string);
      return { success: true, data: result };
    }

    if (commandId === 'is_root_dir') {
      const { isRootDir } = await import('$lib/utils/bms/scanner.js');
      const result = await isRootDir(params.dirPath as string);
      return { success: true, data: result };
    }

    if (commandId === 'extract_work_name') {
      const { extractWorkName } = await import('$lib/utils/bms/work.js');
      const result = await extractWorkName(params.titles as string[], params.removeUnlosedPair as boolean, params.removeTailingSignList as string[]);
      return { success: true, data: result };
    }

    if (commandId === 'root_event_check_num_folder') {
      const { checkNumFolder } = await import('$lib/utils/event/folder.js');
      const result = await checkNumFolder(params.dir as string, params.max as number);
      return { success: true, data: result };
    }

    if (commandId === 'root_event_create_num_folders') {
      const { createNumFolders } = await import('$lib/utils/event/folder.js');
      await createNumFolders(params.dir as string, params.max as number);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_event_generate_work_info_table') {
      const { generateWorkInfoTable } = await import('$lib/utils/event/folder.js');
      const result = await generateWorkInfoTable(params.rootDir as string);
      return { success: true, data: result };
    }

    if (commandId === 'root_event_jump_to_work_info') {
      const { jumpToWorkInfo } = await import('$lib/utils/event/jumpToWorkInfo.js');
      await jumpToWorkInfo(params.event as BMSEvent, params.workIds as number[]);
      return { success: true, data: undefined };
    }

    if (commandId === 'remove_empty_folders') {
      const { removeEmptyFolders } = await import('$lib/utils/fs/cleanup.js');
      await removeEmptyFolders(params.parentDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_get_media_info') {
      const { getMediaInfo } = await import('$lib/utils/media/index.js');
      const result = await getMediaInfo(params.filePath as string);
      return { success: true, data: result };
    }

    if (commandId === 'work_get_video_info') {
      const { getVideoInfo } = await import('$lib/utils/media/index.js');
      const result = await getVideoInfo(params.filePath as string);
      return { success: true, data: result };
    }

    if (commandId === 'work_get_video_size') {
      const { getVideoSize } = await import('$lib/utils/media/index.js');
      const result = await getVideoSize(params.filePath as string);
      return { success: true, data: result };
    }

    if (commandId === 'work_get_media_duration') {
      const { getMediaDuration } = await import('$lib/utils/media/index.js');
      const result = await getMediaDuration(params.filePath as string);
      return { success: true, data: result };
    }

    if (commandId === 'work_remove_zero_sized_media_files') {
      const { removeZeroSizedMediaFiles } = await import('$lib/utils/media/index.js');
      await removeZeroSizedMediaFiles(params.dir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_remove_unneed_media_files') {
      const { removeUnneedMediaFiles } = await import('$lib/utils/media/index.js');
      await removeUnneedMediaFiles(params.rootDir as string, params.preset as RemoveMediaPreset);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_transfer_audio') {
      const { transferAudio } = await import('$lib/utils/media/index.js');
      await transferAudio(params.rootDir as string, params.presetNames as AudioPreset[], params.removeOriginFileWhenSuccess as boolean, params.removeOriginFileWhenFailed as boolean, params.skipOnFail as boolean, params.progressManager as IProgressManager);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_transfer_video') {
      const { transferVideo } = await import('$lib/utils/media/index.js');
      await transferVideo(params.rootDir as string, params.presetNames as VideoPreset[], params.removeOriginFile as boolean, params.removeExistingTargetFile as boolean, params.usePrefered as boolean, params.progressManager as IProgressManager);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_set_name_by_bms') {
      const { setNameByBms } = await import('$lib/utils/work/rename.js');
      await setNameByBms(params.workDir as string, params.setType as BmsFolderSetNameType, params.dryRun as boolean, params.replacePreset as ReplacePreset, params.skipAlreadyFormatted as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_undo_set_name_by_bms') {
      const { undoSetNameByBms } = await import('$lib/utils/work/rename.js');
      await undoSetNameByBms(params.workDir as string, params.setType as BmsFolderSetNameType, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_append_artist_name_by_bms') {
      const { appendArtistNameByBms } = await import('$lib/utils/work/rename.js');
      await appendArtistNameByBms(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_set_name_by_bms_optimized') {
      const { setNameByBmsOptimized } = await import('$lib/utils/work/rename.js');
      const result = await setNameByBmsOptimized(params.workDir as string, params.setType as BmsFolderSetNameType, params.dryRun as boolean, params.replacePreset as ReplacePreset);
      return { success: true, data: result };
    }

    if (commandId === 'root_root_set_name_by_bms') {
      const { rootSetNameByBms } = await import('$lib/utils/root/batch.js');
      await rootSetNameByBms(params.rootDir as string, params.setType as BmsFolderSetNameType, params.dryRun as boolean, params.replacePreset as ReplacePreset);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_root_undo_set_name_by_bms') {
      const { rootUndoSetNameByBms } = await import('$lib/utils/root/batch.js');
      await rootUndoSetNameByBms(params.rootDir as string, params.setType as BmsFolderSetNameType, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_copy_numbered_workdir_names') {
      const { copyNumberedWorkdirNames } = await import('$lib/utils/root/batch.js');
      await copyNumberedWorkdirNames(params.fromDir as string, params.toDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'pack_setup_rawpack_to_hq') {
      const { setupRawpackToHq } = await import('$lib/utils/pack/pack.js');
      await setupRawpackToHq(params.packDir as string, params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'pack_update_rawpack_to_hq') {
      const { updateRawpackToHq } = await import('$lib/utils/pack/pack.js');
      await updateRawpackToHq(params.packDir as string, params.rootDir as string, params.syncDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'pack_pack_hq_to_lq') {
      const { packHqToLq } = await import('$lib/utils/pack/pack.js');
      await packHqToLq(params.rootDir as string, params.dryRun as boolean, params.progressManager as IProgressManager);
      return { success: true, data: undefined };
    }

    if (commandId === 'pack_pack_raw_to_hq') {
      const { packRawToHq } = await import('$lib/utils/pack/pack.js');
      await packRawToHq(params.rootDir as string, params.dryRun as boolean, params.progressManager as IProgressManager);
      return { success: true, data: undefined };
    }

    if (commandId === 'scan_folder_similar_folders') {
      const { scanFolderSimilarFolders } = await import('$lib/utils/bms/folder.js');
      const result = await scanFolderSimilarFolders(params.rootDir as string, params.similarityTrigger as number);
      return { success: true, data: result };
    }

    if (commandId === 'set_name_by_bms') {
      const { setNameByBms } = await import('$lib/utils/bms/folder.js');
      const result = await setNameByBms(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: result };
    }

    if (commandId === 'append_name_by_bms') {
      const { appendNameByBms } = await import('$lib/utils/bms/folder.js');
      const result = await appendNameByBms(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: result };
    }

    if (commandId === 'append_artist_name_by_bms') {
      const { appendArtistNameByBms } = await import('$lib/utils/bms/folder.js');
      const result = await appendArtistNameByBms(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: result };
    }

    if (commandId === 'copy_numbered_workdir_names') {
      const { copyNumberedWorkdirNames } = await import('$lib/utils/bms/folder.js');
      const result = await copyNumberedWorkdirNames(params.rootDirFrom as string, params.rootDirTo as string, params.dryRun as boolean);
      return { success: true, data: result };
    }

    if (commandId === 'undo_set_name') {
      const { undoSetName } = await import('$lib/utils/bms/folder.js');
      const result = await undoSetName(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: result };
    }

    if (commandId === 'check_ffmpeg_exec') {
      const { checkFfmpegExec } = await import('$lib/utils/system/check.js');
      const result = await checkFfmpegExec();
      return { success: true, data: result };
    }

    if (commandId === 'check_flac_exec') {
      const { checkFlacExec } = await import('$lib/utils/system/check.js');
      const result = await checkFlacExec();
      return { success: true, data: result };
    }

    if (commandId === 'check_oggenc_exec') {
      const { checkOggencExec } = await import('$lib/utils/system/check.js');
      const result = await checkOggencExec();
      return { success: true, data: result };
    }

    return {
      success: false,
      error: '未知的前端命令'
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error)
    };
  }
}

/**
 * 获取所有前端命令 ID
 */
export const FRONTEND_COMMAND_IDS: string[] = [
  'is_dir_having_file',
  'is_dir_having_content',
  'wasted_fix',
  'rawpack_batch_rename_with_num',
  'rawpack_unzip_numeric_to_bms_folder',
  'rawpack_unzip_with_name_to_bms_folder',
  'root_split_folders_with_first_char',
  'root_undo_split_pack',
  'root_move_works_in_pack',
  'root_move_out_works',
  'root_merge_folders_with_same_name_within_dir',
  'root_move_works_in_pack_python',
  'root_move_works_with_same_name_to_siblings',
  'root_move_works_with_same_name',
  'root_merge_split_folders',
  'root_scan_similar_folders',
  'read_and_parse_bms_file',
  'get_dir_bms_list',
  'get_dir_bms_info',
  'is_work_dir',
  'is_root_dir',
  'extract_work_name',
  'root_event_check_num_folder',
  'root_event_create_num_folders',
  'root_event_generate_work_info_table',
  'root_event_jump_to_work_info',
  'remove_empty_folders',
  'work_get_media_info',
  'work_get_video_info',
  'work_get_video_size',
  'work_get_media_duration',
  'work_remove_zero_sized_media_files',
  'work_remove_unneed_media_files',
  'work_transfer_audio',
  'work_transfer_video',
  'work_set_name_by_bms',
  'work_undo_set_name_by_bms',
  'work_append_artist_name_by_bms',
  'work_set_name_by_bms_optimized',
  'root_root_set_name_by_bms',
  'root_root_undo_set_name_by_bms',
  'root_copy_numbered_workdir_names',
  'pack_setup_rawpack_to_hq',
  'pack_update_rawpack_to_hq',
  'pack_pack_hq_to_lq',
  'pack_pack_raw_to_hq',
  'scan_folder_similar_folders',
  'set_name_by_bms',
  'append_name_by_bms',
  'append_artist_name_by_bms',
  'copy_numbered_workdir_names',
  'undo_set_name',
  'check_ffmpeg_exec',
  'check_flac_exec',
  'check_oggenc_exec'
];
