/**
 * 自动生成的前端命令路由
 *
 * @generated
 * DO NOT EDIT THIS FILE MANUALLY
 */

import type { CommandResult } from '$lib/types/api.js';
import type { AeryFixParams, BmsFolderSetNameType, IProgressManager, RemoveMediaPreset, ReplacePreset, SetFileNumParams } from '$lib/types/enums.js';

/**
 * 自动生成的前端命令执行函数
 */
export async function executeGeneratedFrontendCommand(
  commandId: string,
  params: Record<string, unknown>
): Promise<CommandResult> {
  try {
    if (commandId === 'is_dir_having_file') {
      const { isDirHavingFile } = await import('$lib/utils/fs/compare.js');
      const result = await isDirHavingFile(params.dirPath as string);
      return { success: true, data: result };
    }

    if (commandId === 'read_and_parse_bms_file') {
      const { readAndParseBmsFile } = await import('$lib/utils/bms/scanner.js');
      const result = await readAndParseBmsFile(params.filePath as string);
      return { success: true, data: result };
    }

    if (commandId === 'get_dir_bms_list') {
      const { getDirBmsList } = await import('$lib/utils/bms/scanner.js');
      const result = await getDirBmsList(params.dirPath as string);
      return { success: true, data: result };
    }

    if (commandId === 'get_dir_bms_info') {
      const { getDirBmsInfo } = await import('$lib/utils/bms/scanner.js');
      const result = await getDirBmsInfo(params.dirPath as string);
      return { success: true, data: result };
    }

    if (commandId === 'is_work_dir') {
      const { isWorkDir } = await import('$lib/utils/bms/scanner.js');
      const result = await isWorkDir(params.dirPath as string);
      return { success: true, data: result };
    }

    if (commandId === 'is_root_dir') {
      const { isRootDir } = await import('$lib/utils/bms/scanner.js');
      const result = await isRootDir(params.dirPath as string);
      return { success: true, data: result };
    }

    if (commandId === 'remove_empty_folders') {
      const { removeEmptyFolders } = await import('$lib/utils/fs/cleanup.js');
      await removeEmptyFolders(params.parentDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_remove_zero_sized_media_files') {
      const { removeZeroSizedMediaFiles } = await import('$lib/utils/media/cleanup.js');
      await removeZeroSizedMediaFiles(params.dir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_remove_unneed_media_files') {
      const { removeUnneedMediaFiles } = await import('$lib/utils/media/cleanup.js');
      await removeUnneedMediaFiles(params.rootDir as string, params.preset as RemoveMediaPreset);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_set_name_by_bms') {
      const { setNameByBms } = await import('$lib/utils/work/rename.js');
      await setNameByBms(params.workDir as string, params.setType as BmsFolderSetNameType, params.dryRun as boolean, params.replacePreset as ReplacePreset, params.skipAlreadyFormatted as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_undo_set_name_by_bms') {
      const { undoSetNameByBms } = await import('$lib/utils/work/rename.js');
      await undoSetNameByBms(params.workDir as string, params.setType as BmsFolderSetNameType, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_append_artist_name_by_bms') {
      const { appendArtistNameByBms } = await import('$lib/utils/work/rename.js');
      await appendArtistNameByBms(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_set_name_by_bms_optimized') {
      const { setNameByBmsOptimized } = await import('$lib/utils/work/rename.js');
      const result = await setNameByBmsOptimized(params.workDir as string, params.setType as BmsFolderSetNameType, params.dryRun as boolean, params.replacePreset as ReplacePreset);
      return { success: true, data: result };
    }

    if (commandId === 'root_root_set_name_by_bms') {
      const { rootSetNameByBms } = await import('$lib/utils/root/batch.js');
      await rootSetNameByBms(params.rootDir as string, params.setType as BmsFolderSetNameType, params.dryRun as boolean, params.replacePreset as ReplacePreset);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_root_undo_set_name_by_bms') {
      const { rootUndoSetNameByBms } = await import('$lib/utils/root/batch.js');
      await rootUndoSetNameByBms(params.rootDir as string, params.setType as BmsFolderSetNameType, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_copy_numbered_workdir_names') {
      const { copyNumberedWorkdirNames } = await import('$lib/utils/root/batch.js');
      await copyNumberedWorkdirNames(params.fromDir as string, params.toDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_merge_split_folders') {
      const { mergeSplitFolders } = await import('$lib/utils/bigpack/merge.js');
      await mergeSplitFolders(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_scan_similar_folders') {
      const { scanSimilarFolders } = await import('$lib/utils/bigpack/similarity.js');
      const result = await scanSimilarFolders(params.rootDir as string, params.similarityTrigger as number);
      return { success: true, data: result };
    }

    if (commandId === 'extract_work_name') {
      const { extractWorkName } = await import('$lib/utils/bms/work.js');
      const result = await extractWorkName(params.titles as string[], params.removeUnlosedPair as boolean, params.removeTailingSignList as string[]);
      return { success: true, data: result };
    }

    if (commandId === 'pack_pack_hq_to_lq') {
      const { packHqToLq } = await import('$lib/utils/pack/pack.js');
      await packHqToLq(params.rootDir as string, params.dryRun as boolean, params.progressManager as IProgressManager);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_split_folders_with_first_char') {
      const { splitFoldersWithFirstChar } = await import('$lib/utils/bigpack/split.js');
      await splitFoldersWithFirstChar(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'root_move_works_with_same_name_to_siblings') {
      const { moveWorksWithSameNameToSiblings } = await import('$lib/utils/bigpack/split.js');
      await moveWorksWithSameNameToSiblings(params.rootDir as string, params.dryRun as boolean);
      return { success: true, data: undefined };
    }

    if (commandId === 'work_get_media_info') {
      const { getMediaInfo } = await import('$lib/utils/media/probe.js');
      const result = await getMediaInfo(params.filePath as string);
      return { success: true, data: result };
    }

    if (commandId === 'work_get_video_info') {
      const { getVideoInfo } = await import('$lib/utils/media/probe.js');
      const result = await getVideoInfo(params.filePath as string);
      return { success: true, data: result };
    }

    if (commandId === 'work_get_video_size') {
      const { getVideoSize } = await import('$lib/utils/media/probe.js');
      const result = await getVideoSize(params.filePath as string);
      return { success: true, data: result };
    }

    if (commandId === 'work_get_media_duration') {
      const { getMediaDuration } = await import('$lib/utils/media/probe.js');
      const result = await getMediaDuration(params.filePath as string);
      return { success: true, data: result };
    }

    if (commandId === 'rawpack_batch_rename_with_num') {
      const { batchRenameWithNum } = await import('$lib/utils/rawpack/numbering.js');
      const result = await batchRenameWithNum(params.params as SetFileNumParams);
      return { success: true, data: result };
    }

    if (commandId === 'wasted_fix') {
      const { fix } = await import('$lib/utils/wasted/aery_fix.js');
      await fix(params.params as AeryFixParams);
      return { success: true, data: undefined };
    }

    return {
      success: false,
      error: '未知的前端命令'
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error)
    };
  }
}

/**
 * 获取所有前端命令 ID
 */
export const FRONTEND_COMMAND_IDS: string[] = [
  'is_dir_having_file',
  'read_and_parse_bms_file',
  'get_dir_bms_list',
  'get_dir_bms_info',
  'is_work_dir',
  'is_root_dir',
  'remove_empty_folders',
  'work_remove_zero_sized_media_files',
  'work_remove_unneed_media_files',
  'work_set_name_by_bms',
  'work_undo_set_name_by_bms',
  'work_append_artist_name_by_bms',
  'work_set_name_by_bms_optimized',
  'root_root_set_name_by_bms',
  'root_root_undo_set_name_by_bms',
  'root_copy_numbered_workdir_names',
  'root_merge_split_folders',
  'root_scan_similar_folders',
  'extract_work_name',
  'pack_pack_hq_to_lq',
  'root_split_folders_with_first_char',
  'root_move_works_with_same_name_to_siblings',
  'work_get_media_info',
  'work_get_video_info',
  'work_get_video_size',
  'work_get_media_duration',
  'rawpack_batch_rename_with_num',
  'wasted_fix'
];
