/**
 * 自动生成的命令注册表
 *
 * @generated
 * DO NOT EDIT THIS FILE MANUALLY
 */

import type { CommandDefinition } from '$lib/types/commands.js';
import { CommandCategory, ParameterType } from '$lib/types/enums.js';

/**
 * 自动生成的命令注册表
 */
export const GENERATED_COMMAND_REGISTRY: CommandDefinition[] = [
  {
    id: 'is_dir_having_file',
    name: '检查目录文件',
    category: CommandCategory.BMSFolder,
    description: `检查目录是否包含文件`,
    parameters: [
      {
        key: 'dirPath',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 目录路径`
      }
    ],
    returnType: 'boolean',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'is_dir_having_content',
    name: '检查目录内容',
    category: CommandCategory.BMSFolder,
    description: `检查目录是否包含任何内容（文件或目录）`,
    parameters: [
      {
        key: 'dirPath',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 目录路径`
      }
    ],
    returnType: 'boolean',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'wasted_fix',
    name: 'Aery 标签作品修复',
    category: CommandCategory.Wasted,
    description: `处理 Aery 标签作品的特殊合并逻辑，根据相似度阈值合并相似文件夹`,
    parameters: [
      {
        key: 'params',
        type: ParameterType.Enum,
        typeString: 'AeryFixParams',
        required: true,
        description: ``
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'rawpack_batch_rename_with_num',
    name: '批量添加文件编号',
    category: CommandCategory.Pack,
    description: `为多个文件添加编号前缀`,
    parameters: [
      {
        key: 'params',
        type: ParameterType.Enum,
        typeString: 'SetFileNumParams',
        required: true,
        description: `- 编号设置参数`
      }
    ],
    returnType: 'RenameOperation[]',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'rawpack_unzip_numeric_to_bms_folder',
    name: '解压编号压缩包',
    category: CommandCategory.Pack,
    description: `将赋予编号的文件，解压或放置至指定根目录下，带对应编号的作品目录（自动处理文件夹嵌套）`,
    parameters: [
      {
        key: 'packDir',
        type: ParameterType.String,
        typeString: 'string',
        required: true,
        description: `- 压缩包目录`
      },
      {
        key: 'cacheDir',
        type: ParameterType.String,
        typeString: 'string',
        required: true,
        description: `- 缓存目录`
      },
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录`
      },
      {
        key: 'confirm',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 是否确认`
      },
      {
        key: 'replacePreset',
        type: ParameterType.Enum,
        typeString: 'ReplacePreset',
        required: true,
        description: `- 文件替换策略`,
        defaultValue: "ReplacePreset.Default"
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'rawpack_unzip_with_name_to_bms_folder',
    name: '解压命名压缩包',
    category: CommandCategory.Pack,
    description: `将文件，解压或放置至指定根目录下，对应原文件名的作品目录（自动处理文件夹嵌套）`,
    parameters: [
      {
        key: 'packDir',
        type: ParameterType.String,
        typeString: 'string',
        required: true,
        description: `- 压缩包目录`
      },
      {
        key: 'cacheDir',
        type: ParameterType.String,
        typeString: 'string',
        required: true,
        description: `- 缓存目录`
      },
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录`
      },
      {
        key: 'confirm',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 是否确认`
      },
      {
        key: 'replacePreset',
        type: ParameterType.Enum,
        typeString: 'ReplacePreset',
        required: true,
        description: `- 文件替换策略`,
        defaultValue: "ReplacePreset.Default"
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_split_folders_with_first_char',
    name: '按首字符拆分文件夹',
    category: CommandCategory.BigPack,
    description: `将目录下的作品按照首字符规则分成多个文件夹`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 是否模拟运行`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_undo_split_pack',
    name: '撤销拆分',
    category: CommandCategory.BigPack,
    description: `撤销按首字符拆分的操作，将所有子文件夹移回根目录`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_move_works_in_pack',
    name: '移动包内作品',
    category: CommandCategory.BigPack,
    description: `将目录A下的作品，移动到目录B（自动合并）`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'targetPackName',
        type: ParameterType.String,
        typeString: 'string',
        required: true,
        description: `- 目标包名称`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_move_out_works',
    name: '移出一层目录',
    category: CommandCategory.BigPack,
    description: `将子包中的作品移出，合并到根目录`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'sourcePackName',
        type: ParameterType.String,
        typeString: 'string',
        required: true,
        description: `- 源包名称`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_merge_folders_with_same_name_within_dir',
    name: '合并同名作品',
    category: CommandCategory.BigPack,
    description: `合并同一目录中名称相同的文件夹`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_move_works_in_pack_python',
    name: '移动作品包',
    category: CommandCategory.BigPack,
    description: `将目录A下的作品，移动到目录B（自动合并）`,
    parameters: [
      {
        key: 'fromDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 源目录路径`
      },
      {
        key: 'toDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 目标目录路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_move_works_with_same_name_to_siblings',
    name: '移动同名作品到平级目录',
    category: CommandCategory.BigPack,
    description: `将目录中文件名相似的子文件夹合并到各平级目录中`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_move_works_with_same_name',
    name: '合并同名作品',
    category: CommandCategory.BigPack,
    description: `将源文件夹中名称相似的子文件夹合并到目标文件夹中的对应子文件夹`,
    parameters: [
      {
        key: 'fromDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 源文件夹路径`
      },
      {
        key: 'toDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 目标文件夹路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_merge_split_folders',
    name: '合并带艺术家的文件夹',
    category: CommandCategory.BigPack,
    description: `将形如 "Title [Artist]" 的文件夹内容合并到 "Title" 文件夹中`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_scan_similar_folders',
    name: '扫描相似文件夹',
    category: CommandCategory.BMSFolder,
    description: `扫描指定目录中名称相似的文件夹，用于发现重复或误操作`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 要扫描的目录路径`
      },
      {
        key: 'similarityTrigger',
        type: ParameterType.Number,
        typeString: 'number',
        required: false,
        description: `- 相似度触发阈值（默认 0.7）`
      }
    ],
    returnType: '{ folder1: string; folder2: string; similarity: number; }[]',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'read_and_parse_bms_file',
    name: '解析 BMS 文件',
    category: CommandCategory.BMS,
    description: `解析单个 BMS 文件，提取元数据信息（标题、艺术家等）`,
    parameters: [
      {
        key: 'filePath',
        type: ParameterType.File,
        typeString: 'string',
        required: true,
        description: `- BMS 文件路径`
      }
    ],
    returnType: 'BmsOutput | null',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'get_dir_bms_list',
    name: '扫描目录 BMS 文件',
    category: CommandCategory.BMS,
    description: `扫描目录，解析所有 BMS 文件`,
    parameters: [
      {
        key: 'dirPath',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 目录路径`
      }
    ],
    returnType: 'BmsOutput[]',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'get_dir_bms_info',
    name: '读取目录 BMS 信息',
    category: CommandCategory.BMS,
    description: `从目录的 info.toml 文件读取 BMS 摘要信息`,
    parameters: [
      {
        key: 'dirPath',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- BMS 工作目录路径`
      }
    ],
    returnType: 'BmsOutput | null',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'is_work_dir',
    name: '检查工作目录',
    category: CommandCategory.BMS,
    description: `检查指定目录是否为有效的 BMS 工作目录`,
    parameters: [
      {
        key: 'dirPath',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 要检查的目录路径`
      }
    ],
    returnType: 'boolean',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'is_root_dir',
    name: '检查根目录',
    category: CommandCategory.BMS,
    description: `检查指定目录是否为根目录（包含工作目录的目录）`,
    parameters: [
      {
        key: 'dirPath',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 要检查的目录路径`
      }
    ],
    returnType: 'boolean',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'extract_work_name',
    name: '提取作品名称',
    category: CommandCategory.BMS,
    description: `从多个 BMS 标题中提取共同的作品名`,
    parameters: [
      {
        key: 'titles',
        type: ParameterType.String,
        typeString: 'string[]',
        required: true,
        description: `- 包含多个 BMS 标题的列表`
      },
      {
        key: 'removeUnlosedPair',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: false,
        description: `- 是否移除未闭合括号及其后续内容`
      },
      {
        key: 'removeTailingSignList',
        type: ParameterType.String,
        typeString: 'string[]',
        required: false,
        description: `- 要移除的尾部符号列表`
      }
    ],
    returnType: 'string',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'root_event_check_num_folder',
    name: '检查编号文件夹',
    category: CommandCategory.BMSEvent,
    description: `检查各个编号对应的文件夹是否存在`,
    parameters: [
      {
        key: 'dir',
        type: ParameterType.String,
        typeString: 'string',
        required: true,
        description: `- 目录路径`
      },
      {
        key: 'max',
        type: ParameterType.Number,
        typeString: 'number',
        required: true,
        description: `- 最大编号`
      }
    ],
    returnType: 'string[]',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'root_event_create_num_folders',
    name: '创建编号文件夹',
    category: CommandCategory.BMSEvent,
    description: `创建只带有编号的空文件夹`,
    parameters: [
      {
        key: 'dir',
        type: ParameterType.String,
        typeString: 'string',
        required: true,
        description: `- 目录路径`
      },
      {
        key: 'max',
        type: ParameterType.Number,
        typeString: 'number',
        required: true,
        description: `- 最大编号`
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_event_generate_work_info_table',
    name: '生成作品信息表',
    category: CommandCategory.BMSEvent,
    description: `生成活动作品的xlsx表格数据`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      }
    ],
    returnType: 'WorkInfoRow[]',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'root_event_jump_to_work_info',
    name: '跳转至作品目录',
    category: CommandCategory.BMSEvent,
    description: `打开浏览器跳转到BMS活动作品目录页面`,
    parameters: [
      {
        key: 'event',
        type: ParameterType.Enum,
        typeString: 'BMSEvent',
        required: true,
        description: `- BMS 活动类型`
      },
      {
        key: 'workIds',
        type: ParameterType.NumberArray,
        typeString: 'number[]',
        required: false,
        description: `- 作品 ID 列表（可选，为空时跳转到活动列表）`
      }
    ],
    returnType: 'void',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'remove_empty_folders',
    name: '删除空文件夹',
    category: CommandCategory.BMSFolder,
    description: `递归删除指定目录下的所有空文件夹`,
    parameters: [
      {
        key: 'parentDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 要清理的目录路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际删除）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'work_get_media_info',
    name: '获取媒体文件信息',
    category: CommandCategory.Media,
    description: `使用 ffprobe 获取音频或视频文件的详细信息`,
    parameters: [
      {
        key: 'filePath',
        type: ParameterType.File,
        typeString: 'string',
        required: true,
        description: `- 媒体文件路径`
      }
    ],
    returnType: 'MediaInfo | null',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'work_get_video_info',
    name: '获取视频信息',
    category: CommandCategory.Media,
    description: `获取视频文件的尺寸和比特率信息`,
    parameters: [
      {
        key: 'filePath',
        type: ParameterType.File,
        typeString: 'string',
        required: true,
        description: `- 视频文件路径`
      }
    ],
    returnType: 'VideoInfo | null',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'work_get_video_size',
    name: '获取视频尺寸',
    category: CommandCategory.Media,
    description: `获取视频文件的宽度和高度`,
    parameters: [
      {
        key: 'filePath',
        type: ParameterType.File,
        typeString: 'string',
        required: true,
        description: `- 视频文件路径`
      }
    ],
    returnType: '{ width: number; height: number; } | null',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'work_get_media_duration',
    name: '获取媒体时长',
    category: CommandCategory.Media,
    description: `获取音频或视频文件的时长（秒）`,
    parameters: [
      {
        key: 'filePath',
        type: ParameterType.File,
        typeString: 'string',
        required: true,
        description: `- 媒体文件路径`
      }
    ],
    returnType: 'number | null',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'work_remove_zero_sized_media_files',
    name: '删除零字节媒体文件',
    category: CommandCategory.BMSFolder,
    description: `递归删除工作目录中所有零字节媒体文件`,
    parameters: [
      {
        key: 'dir',
        type: ParameterType.String,
        typeString: 'string',
        required: true,
        description: `- 工作目录路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际删除）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'work_remove_unneed_media_files',
    name: '删除重复格式媒体文件',
    category: CommandCategory.BMSFolder,
    description: `根据预设规则删除重复格式的媒体文件（保留高质量格式）`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'preset',
        type: ParameterType.Enum,
        typeString: 'RemoveMediaPreset',
        required: true,
        description: `- 清理规则预设`,
        defaultValue: "RemoveMediaPreset.Oraja"
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'work_transfer_audio',
    name: '音频文件转换',
    category: CommandCategory.Media,
    description: `转换BMS根目录下的音频文件`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'presetNames',
        type: ParameterType.Enum,
        typeString: 'AudioPreset[]',
        required: true,
        description: `- 目标格式预设名称`
      },
      {
        key: 'removeOriginFileWhenSuccess',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 成功时删除原文件`
      },
      {
        key: 'removeOriginFileWhenFailed',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 失败时删除原文件`
      },
      {
        key: 'skipOnFail',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 遇到失败时跳过`
      },
      {
        key: 'progressManager',
        type: ParameterType.Enum,
        typeString: 'IProgressManager',
        required: false,
        description: `- 进度管理器（可选）`
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'work_transfer_video',
    name: '视频文件转换',
    category: CommandCategory.Media,
    description: `转换BMS根目录下的视频文件`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'presetNames',
        type: ParameterType.Enum,
        typeString: 'VideoPreset[]',
        required: true,
        description: `- 目标格式预设名称`
      },
      {
        key: 'removeOriginFile',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 成功时删除原文件`
      },
      {
        key: 'removeExistingTargetFile',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 删除已存在的目标文件`
      },
      {
        key: 'usePrefered',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 使用推荐预设`
      },
      {
        key: 'progressManager',
        type: ParameterType.Enum,
        typeString: 'IProgressManager',
        required: false,
        description: `- 进度管理器（可选）`
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'work_set_name_by_bms',
    name: '根据 BMS 重命名工作目录',
    category: CommandCategory.BMSFolder,
    description: `根据 BMS 文件信息重命名工作目录，支持多种命名策略`,
    parameters: [
      {
        key: 'workDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 工作目录路径`
      },
      {
        key: 'setType',
        type: ParameterType.Enum,
        typeString: 'BmsFolderSetNameType',
        required: true,
        description: `- 命名方式`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      },
      {
        key: 'replacePreset',
        type: ParameterType.Enum,
        typeString: 'ReplacePreset',
        required: true,
        description: `- 文件替换策略`,
        defaultValue: "ReplacePreset.Default"
      },
      {
        key: 'skipAlreadyFormatted',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 跳过已格式化的目录`
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'work_undo_set_name_by_bms',
    name: '撤销工作目录重命名',
    category: CommandCategory.BMSFolder,
    description: `撤销之前的目录重命名操作，恢复原始目录名`,
    parameters: [
      {
        key: 'workDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 工作目录路径`
      },
      {
        key: 'setType',
        type: ParameterType.Enum,
        typeString: 'BmsFolderSetNameType',
        required: true,
        description: `- 命名方式`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'work_append_artist_name_by_bms',
    name: '追加艺术家名称',
    category: CommandCategory.BMSFolder,
    description: `在作品文件夹名后追加艺术家名称`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'work_set_name_by_bms_optimized',
    name: '根据 BMS 重命名工作目录（优化版）',
    category: CommandCategory.BMSFolder,
    description: `根据 BMS 文件信息重命名工作目录，支持嵌套目录处理和相似度合并`,
    parameters: [
      {
        key: 'workDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 工作目录路径`
      },
      {
        key: 'setType',
        type: ParameterType.Enum,
        typeString: 'BmsFolderSetNameType',
        required: true,
        description: `- 命名方式`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      },
      {
        key: 'replacePreset',
        type: ParameterType.Enum,
        typeString: 'ReplacePreset',
        required: true,
        description: `- 文件替换策略`,
        defaultValue: "ReplacePreset.Default"
      }
    ],
    returnType: 'boolean',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_root_set_name_by_bms',
    name: '批量重命名工作目录',
    category: CommandCategory.BMSFolder,
    description: `递归为根目录下的所有工作目录设置名称`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'setType',
        type: ParameterType.Enum,
        typeString: 'BmsFolderSetNameType',
        required: true,
        description: `- 命名方式`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      },
      {
        key: 'replacePreset',
        type: ParameterType.Enum,
        typeString: 'ReplacePreset',
        required: true,
        description: `- 文件替换策略`,
        defaultValue: "ReplacePreset.Default"
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_root_undo_set_name_by_bms',
    name: '批量撤销重命名',
    category: CommandCategory.BMSFolder,
    description: `递归撤销根目录下所有工作目录的名称设置`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'setType',
        type: ParameterType.Enum,
        typeString: 'BmsFolderSetNameType',
        required: true,
        description: `- 命名方式`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_copy_numbered_workdir_names',
    name: '复制编号目录名称',
    category: CommandCategory.BMSFolder,
    description: `复制编号目录的名称到目标目录`,
    parameters: [
      {
        key: 'fromDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 源目录路径`
      },
      {
        key: 'toDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 目标目录路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'pack_setup_rawpack_to_hq',
    name: '大包生成脚本：原包 -> HQ版大包',
    category: CommandCategory.Pack,
    description: `快速创建大包，从已编号的原始包到目标BMS文件夹`,
    parameters: [
      {
        key: 'packDir',
        type: ParameterType.String,
        typeString: 'string',
        required: true,
        description: `- 压缩包目录路径`
      },
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 目标根目录路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'pack_update_rawpack_to_hq',
    name: '大包更新脚本：原包 -> HQ版大包',
    category: CommandCategory.Pack,
    description: `快速更新大包，从已编号的原始包到增量BMS文件夹`,
    parameters: [
      {
        key: 'packDir',
        type: ParameterType.String,
        typeString: 'string',
        required: true,
        description: `- 压缩包目录路径`
      },
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 增量根目录路径`
      },
      {
        key: 'syncDir',
        type: ParameterType.String,
        typeString: 'string',
        required: true,
        description: `- 已存在的BMS文件夹路径（用于名称同步和文件检查）`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'pack_pack_hq_to_lq',
    name: 'HQ 版本转 LQ 版本',
    category: CommandCategory.Pack,
    description: `将 HQ 版本转换为 LQ 版本，用于 LR2 玩家`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      },
      {
        key: 'progressManager',
        type: ParameterType.Enum,
        typeString: 'IProgressManager',
        required: false,
        description: ``
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'pack_pack_raw_to_hq',
    name: 'BMS大包脚本：原包 -> HQ版大包',
    category: CommandCategory.Pack,
    description: `将Raw版本转换为HQ版本，用于beatoraja/Qwilight玩家`,
    parameters: [
      {
        key: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        key: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      },
      {
        key: 'progressManager',
        type: ParameterType.Enum,
        typeString: 'IProgressManager',
        required: false,
        description: `- 进度管理器（可选）`
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  }
];

/**
 * 获取命令总数
 */
export const COMMAND_COUNT = 46;
