/**
 * 自动生成的命令注册表
 *
 * @generated
 * DO NOT EDIT THIS FILE MANUALLY
 */

import type { CommandDefinition } from '$lib/types/commands.js';
import { CommandCategory, ParameterType } from '$lib/types/enums.js';

/**
 * 自动生成的命令注册表
 */
export const GENERATED_COMMAND_REGISTRY: CommandDefinition[] = [
  {
    id: 'is_dir_having_file',
    name: '检查目录文件',
    category: CommandCategory.FS,
    description: `检查目录是否包含文件`,
    parameters: [
      {
        name: 'dirPath',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 目录路径`
      }
    ],
    returnType: 'boolean',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'read_and_parse_bms_file',
    name: '解析 BMS 文件',
    category: CommandCategory.BMS,
    description: `解析单个 BMS 文件，提取元数据信息（标题、艺术家等）`,
    parameters: [
      {
        name: 'filePath',
        type: ParameterType.File,
        typeString: 'string',
        required: true,
        description: `- BMS 文件路径`
      }
    ],
    returnType: 'BmsOutput | null',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'get_dir_bms_list',
    name: '扫描目录 BMS 文件',
    category: CommandCategory.BMS,
    description: `扫描目录，解析所有 BMS 文件`,
    parameters: [
      {
        name: 'dirPath',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 目录路径`
      }
    ],
    returnType: 'BmsOutput[]',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'get_dir_bms_info',
    name: '读取目录 BMS 信息',
    category: CommandCategory.BMS,
    description: `从目录的 info.toml 文件读取 BMS 摘要信息`,
    parameters: [
      {
        name: 'dirPath',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- BMS 工作目录路径`
      }
    ],
    returnType: 'BmsOutput | null',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'is_work_dir',
    name: '检查工作目录',
    category: CommandCategory.BMS,
    description: `检查指定目录是否为有效的 BMS 工作目录`,
    parameters: [
      {
        name: 'dirPath',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 要检查的目录路径`
      }
    ],
    returnType: 'boolean',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'is_root_dir',
    name: '检查根目录',
    category: CommandCategory.BMS,
    description: `检查指定目录是否为根目录（包含工作目录的目录）`,
    parameters: [
      {
        name: 'dirPath',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 要检查的目录路径`
      }
    ],
    returnType: 'boolean',
    dangerous: false,
    isFrontendCommand: true
  },
  {
    id: 'remove_empty_folders',
    name: '删除空文件夹',
    category: CommandCategory.FS,
    description: `递归删除指定目录下的所有空文件夹`,
    parameters: [
      {
        name: 'parentDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 要清理的目录路径`
      },
      {
        name: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际删除）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'work_remove_zero_sized_media_files',
    name: '删除零字节媒体文件',
    category: CommandCategory.Work,
    description: `递归删除工作目录中所有零字节媒体文件`,
    parameters: [
      {
        name: 'dir',
        type: ParameterType.String,
        typeString: 'string',
        required: true,
        description: `- 工作目录路径`
      },
      {
        name: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际删除）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'work_remove_unneed_media_files',
    name: '删除重复格式媒体文件',
    category: CommandCategory.Root,
    description: `根据预设规则删除重复格式的媒体文件（保留高质量格式）`,
    parameters: [
      {
        name: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        name: 'preset',
        type: ParameterType.Enum,
        typeString: 'RemoveMediaPreset',
        required: true,
        description: `- 清理规则预设`,
        defaultValue: "RemoveMediaPreset.Oraja"
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'work_set_name_by_bms',
    name: '根据 BMS 重命名工作目录',
    category: CommandCategory.Work,
    description: `根据 BMS 文件信息重命名工作目录，支持多种命名策略`,
    parameters: [
      {
        name: 'workDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 工作目录路径`
      },
      {
        name: 'setType',
        type: ParameterType.Enum,
        typeString: 'BmsFolderSetNameType',
        required: true,
        description: `- 命名方式`
      },
      {
        name: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      },
      {
        name: 'replacePreset',
        type: ParameterType.Enum,
        typeString: 'ReplacePreset',
        required: true,
        description: `- 文件替换策略`,
        defaultValue: "ReplacePreset.Default"
      },
      {
        name: 'skipAlreadyFormatted',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 跳过已格式化的目录`
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'work_undo_set_name_by_bms',
    name: '撤销工作目录重命名',
    category: CommandCategory.Work,
    description: `撤销之前的目录重命名操作，恢复原始目录名`,
    parameters: [
      {
        name: 'workDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 工作目录路径`
      },
      {
        name: 'setType',
        type: ParameterType.Enum,
        typeString: 'BmsFolderSetNameType',
        required: true,
        description: `- 命名方式`
      },
      {
        name: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_root_set_name_by_bms',
    name: '批量重命名工作目录',
    category: CommandCategory.Root,
    description: `递归为根目录下的所有工作目录设置名称`,
    parameters: [
      {
        name: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        name: 'setType',
        type: ParameterType.Enum,
        typeString: 'BmsFolderSetNameType',
        required: true,
        description: `- 命名方式`
      },
      {
        name: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      },
      {
        name: 'replacePreset',
        type: ParameterType.Enum,
        typeString: 'ReplacePreset',
        required: true,
        description: `- 文件替换策略`,
        defaultValue: "ReplacePreset.Default"
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_root_undo_set_name_by_bms',
    name: '批量撤销重命名',
    category: CommandCategory.Root,
    description: `递归撤销根目录下所有工作目录的名称设置`,
    parameters: [
      {
        name: 'rootDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 根目录路径`
      },
      {
        name: 'setType',
        type: ParameterType.Enum,
        typeString: 'BmsFolderSetNameType',
        required: true,
        description: `- 命名方式`
      },
      {
        name: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  },
  {
    id: 'root_copy_numbered_workdir_names',
    name: '复制编号目录名称',
    category: CommandCategory.Root,
    description: `复制编号目录的名称到目标目录`,
    parameters: [
      {
        name: 'fromDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 源目录路径`
      },
      {
        name: 'toDir',
        type: ParameterType.Directory,
        typeString: 'string',
        required: true,
        description: `- 目标目录路径`
      },
      {
        name: 'dryRun',
        type: ParameterType.Boolean,
        typeString: 'boolean',
        required: true,
        description: `- 模拟运行（不实际执行）`,
        defaultValue: true
      }
    ],
    returnType: 'void',
    dangerous: true,
    isFrontendCommand: true
  }
];

/**
 * 获取命令总数
 */
export const COMMAND_COUNT = 14;
